version: "3"

services:
    web:
      container_name: takishop
      restart: always
      build: .
      ports:
        - "9000:9000"
      links:
        - "mongo"
      volumes:
        - .:/usr/src/app
    mongo:
      container_name: takishopdb
      image: mongo
      ports:
        - "27017:27017"